/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    services: Service;
    posts: Post;
    categories: Category;
    testimonials: Testimonial;
    'team-members': TeamMember;
    media: Media;
    enquiries: Enquiry;
    applications: Application;
    redirects: Redirect;
    users: User;
    customers: Customer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Lowercase Latin letters, numbers and hyphens. Used in the URL for both languages.
   */
  slug: string;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            lead?: string | null;
            /**
             * A real photograph. Text over it gets a brand-900 overlay at 55%.
             */
            image?: (number | null) | Media;
            actions?:
              | {
                  label: string;
                  /**
                   * A path such as /services, or a full https:// URL.
                   */
                  href: string;
                  style?: ('primary' | 'secondary' | 'link') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            lead?: string | null;
            source?: ('all' | 'featured' | 'manual') | null;
            services?: (number | Service)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesGrid';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  /**
                   * Western Arabic numerals in both languages, e.g. 235+.
                   */
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            lead?: string | null;
            steps?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'process';
          }
        | {
            heading?: string | null;
            body: string;
            image: number | Media;
            imagePosition?: ('start' | 'end') | null;
            actions?:
              | {
                  label: string;
                  /**
                   * A path such as /services, or a full https:// URL.
                   */
                  href: string;
                  style?: ('primary' | 'secondary' | 'link') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            heading?: string | null;
            member: number | TeamMember;
            actions?:
              | {
                  label: string;
                  /**
                   * A path such as /services, or a full https:// URL.
                   */
                  href: string;
                  style?: ('primary' | 'secondary' | 'link') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'founder';
          }
        | {
            heading?: string | null;
            source?: ('featured' | 'manual') | null;
            testimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            lead?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'latestPosts';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            body?: string | null;
            actions?:
              | {
                  label: string;
                  /**
                   * A path such as /services, or a full https:// URL.
                   */
                  href: string;
                  style?: ('primary' | 'secondary' | 'link') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Put the full enquiry form in this section.
             */
            showEnquiryForm?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  /**
   * Optional. Leave empty to use the page title and summary.
   */
  seo?: {
    /**
     * Around 60 characters. Shown as the blue link in search results.
     */
    title?: string | null;
    /**
     * Around 155 characters. Shown under the link in search results.
     */
    description?: string | null;
    /**
     * 1200 × 630. Falls back to the brand OG image.
     */
    image?: (number | null) | Media;
    /**
     * Keep this page out of search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * JPEG, PNG, WebP, AVIF or PDF. Maximum 8 MB. SVG is not accepted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for screen readers and for when it fails to load. Write it in the language you are editing. Leave a single space for purely decorative images.
   */
  alt: string;
  caption?: string | null;
  /**
   * Photographer or source, if one needs crediting.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Lowercase Latin letters, numbers and hyphens. Used in the URL for both languages.
   */
  slug: string;
  /**
   * One or two sentences, in the customer’s words rather than ours. Shown on the services index and in search results.
   */
  summary: string;
  /**
   * Which group this service is listed under on the services page and in the footer.
   */
  category: 'import' | 'company' | 'banking' | 'ecommerce' | 'visas' | 'consulting';
  /**
   * Single-weight line icon, from the Lucide set (brief section 15).
   */
  icon:
    | 'search'
    | 'factory'
    | 'clipboard-check'
    | 'ship'
    | 'building'
    | 'route'
    | 'shopping-cart'
    | 'lightbulb'
    | 'tent'
    | 'package'
    | 'plane'
    | 'file-check'
    | 'id-card'
    | 'users'
    | 'landmark'
    | 'wallet'
    | 'store'
    | 'calculator'
    | 'map-pin'
    | 'badge-check'
    | 'file-pen';
  /**
   * Starting price in Chinese yuan, whole numbers. Shown as “from ¥8,200”. Leave empty to show no price.
   */
  priceFrom?: number | null;
  /**
   * What the starting price is per.
   */
  priceUnit?: ('once' | 'year' | 'month' | 'class') | null;
  /**
   * A structured request form for this service. When set, the page leads with “Start your application” instead of the general enquiry form.
   */
  applicationType?:
    | (
        | 'consultation'
        | 'company-registration'
        | 'visa-invitation'
        | 'visa'
        | 'product-search'
        | 'shipping-quote'
        | 'account-opening'
        | 'store-setup'
        | 'trademark'
      )
    | null;
  /**
   * The flagship offering. Shown larger on the services index and the homepage.
   */
  featured?: boolean | null;
  /**
   * Lower numbers come first.
   */
  order: number;
  /**
   * A real photograph — a factory floor, an inspection, a container. Not stock (brief section 15).
   */
  image?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Concrete, checkable points. Say what happens, in what order.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Documents and information the client must have ready — a passport copy, three company names, a business licence. Shown as a checklist on the page and repeated on the application form.
   */
  requirements?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  relatedServices?: (number | Service)[] | null;
  /**
   * Optional. Leave empty to use the page title and summary.
   */
  seo?: {
    /**
     * Around 60 characters. Shown as the blue link in search results.
     */
    title?: string | null;
    /**
     * Around 155 characters. Shown under the link in search results.
     */
    description?: string | null;
    /**
     * 1200 × 630. Falls back to the brand OG image.
     */
    image?: (number | null) | Media;
    /**
     * Keep this page out of search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * Lowercase Latin letters, numbers and hyphens. Used in the URL for both languages.
   */
  slug: string;
  role: string;
  photo?: (number | null) | Media;
  /**
   * Lead with what they do for the customer, not a CV.
   */
  bio?: string | null;
  /**
   * Real numbers. 235+ cities. 100+ trade fairs. Named awards.
   */
  credentials?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  isFounder?: boolean | null;
  order?: number | null;
  links?: {
    instagram?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
    email?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Real words from real customers. Brief section 10: never stock-photo optimism — if a quote reads like marketing, do not publish it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  /**
   * e.g. importer, Riyadh
   */
  role?: string | null;
  /**
   * ISO 3166-1 alpha-2, e.g. SA.
   */
  country?: string | null;
  avatar?: (number | null) | Media;
  serviceUsed?: (number | null) | Service;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Lowercase Latin letters, numbers and hyphens. Used in the URL for both languages.
   */
  slug: string;
  /**
   * Shown on the blog index and as the search-result description.
   */
  excerpt: string;
  coverImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt: string;
  author?: (number | null) | TeamMember;
  categories?: (number | Category)[] | null;
  /**
   * Calculated on save, per language.
   */
  readingMinutes?: number | null;
  relatedPosts?: (number | Post)[] | null;
  /**
   * Optional. Leave empty to use the page title and summary.
   */
  seo?: {
    /**
     * Around 60 characters. Shown as the blue link in search results.
     */
    title?: string | null;
    /**
     * Around 155 characters. Shown under the link in search results.
     */
    description?: string | null;
    /**
     * 1200 × 630. Falls back to the brand OG image.
     */
    image?: (number | null) | Media;
    /**
     * Keep this page out of search engines.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Lowercase Latin letters, numbers and hyphens. Used in the URL for both languages.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every submission from the website form. Nothing here is public.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  reference: string;
  status: 'new' | 'contacted' | 'quoted' | 'won' | 'lost' | 'spam';
  assignedTo?: (number | null) | User;
  /**
   * Phase 2 — links this enquiry to a client portal account.
   */
  customer?: (number | null) | Customer;
  name: string;
  country: string;
  /**
   * E.164, e.g. +966501234567.
   */
  whatsapp: string;
  email?: string | null;
  /**
   * Empty when the visitor chose “something else”, or skipped the question.
   */
  service?: (number | null) | Service;
  /**
   * Set when the visitor chose “something else”. Blank means they skipped the question.
   */
  serviceOther?: string | null;
  message: string;
  /**
   * Never leaves the CMS.
   */
  internalNotes?: string | null;
  /**
   * Captured automatically. Useful when judging whether a lead is genuine.
   */
  meta?: {
    locale?: ('ar' | 'en') | null;
    sourcePath?: string | null;
    referrer?: string | null;
    userAgent?: string | null;
    /**
     * Network prefix only; the full address is never stored.
     */
    ipPrefix?: string | null;
    submittedAt?: string | null;
  };
  /**
   * When the notification email was accepted by the provider. Empty means it failed — the enquiry is still safe here.
   */
  notifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  /**
   * Enrol with: npm run totp:enrol -- <email>
   */
  totpEnabled?: boolean | null;
  totpSecret?: string | null;
  backupCodes?:
    | {
        hash: string;
        usedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Phase 2 — the client portal. No public sign-up or login route exists yet; these records are here so the schema does not have to change when it does.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  fullName: string;
  company?: string | null;
  /**
   * ISO 3166-1 alpha-2, e.g. SA, YE, AE.
   */
  country?: string | null;
  whatsapp?: string | null;
  role: 'owner' | 'member';
  preferredLocale?: ('ar' | 'en') | null;
  /**
   * Internal. Never shown to the customer.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * Structured requests from the application forms — company registration, visas, accounts, store setup, quotes. Nothing here is public.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  reference: string;
  type:
    | 'consultation'
    | 'company-registration'
    | 'visa-invitation'
    | 'visa'
    | 'product-search'
    | 'shipping-quote'
    | 'account-opening'
    | 'store-setup'
    | 'trademark';
  status: 'new' | 'contacted' | 'documents' | 'in-progress' | 'completed' | 'lost' | 'spam';
  assignedTo?: (number | null) | User;
  /**
   * The service page the visitor started from, when there was one.
   */
  service?: (number | null) | Service;
  name: string;
  country: string;
  /**
   * E.164, e.g. +966501234567.
   */
  whatsapp: string;
  email?: string | null;
  /**
   * One line summarising the request, built from the answers.
   */
  headline?: string | null;
  /**
   * The answers, exactly as validated. Field names match the form.
   */
  details:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Never leaves the CMS.
   */
  internalNotes?: string | null;
  /**
   * Captured automatically. Useful when judging whether a request is genuine.
   */
  meta?: {
    locale?: ('ar' | 'en') | null;
    sourcePath?: string | null;
    referrer?: string | null;
    userAgent?: string | null;
    /**
     * Network prefix only; the full address is never stored.
     */
    ipPrefix?: string | null;
    submittedAt?: string | null;
  };
  /**
   * When the notification email was accepted by the provider. Empty means it failed — the request is still safe here.
   */
  notifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Old URLs that should send visitors somewhere new, and injected spam URLs that should be told they are gone for good.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Path only, starting with a slash, no domain. e.g. /en/home/ — matched with and without the trailing slash.
   */
  from: string;
  type: '301' | '308' | '302' | '410';
  /**
   * Where to send them. Leave empty for a 410.
   */
  to?: string | null;
  enabled?: boolean | null;
  /**
   * Why this exists. Future you will want to know.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              lead?: T;
              image?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        servicesGrid?:
          | T
          | {
              heading?: T;
              lead?: T;
              source?: T;
              services?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              heading?: T;
              lead?: T;
              steps?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              imagePosition?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        founder?:
          | T
          | {
              heading?: T;
              member?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              source?: T;
              testimonials?: T;
              id?: T;
              blockName?: T;
            };
        latestPosts?:
          | T
          | {
              heading?: T;
              lead?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              showEnquiryForm?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  category?: T;
  icon?: T;
  priceFrom?: T;
  priceUnit?: T;
  applicationType?: T;
  featured?: T;
  order?: T;
  image?: T;
  body?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedServices?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  body?: T;
  publishedAt?: T;
  author?: T;
  categories?: T;
  readingMinutes?: T;
  relatedPosts?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  country?: T;
  avatar?: T;
  serviceUsed?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  photo?: T;
  bio?: T;
  credentials?:
    | T
    | {
        text?: T;
        id?: T;
      };
  isFounder?: T;
  order?: T;
  links?:
    | T
    | {
        instagram?: T;
        youtube?: T;
        linkedin?: T;
        email?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  reference?: T;
  status?: T;
  assignedTo?: T;
  customer?: T;
  name?: T;
  country?: T;
  whatsapp?: T;
  email?: T;
  service?: T;
  serviceOther?: T;
  message?: T;
  internalNotes?: T;
  meta?:
    | T
    | {
        locale?: T;
        sourcePath?: T;
        referrer?: T;
        userAgent?: T;
        ipPrefix?: T;
        submittedAt?: T;
      };
  notifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  reference?: T;
  type?: T;
  status?: T;
  assignedTo?: T;
  service?: T;
  name?: T;
  country?: T;
  whatsapp?: T;
  email?: T;
  headline?: T;
  details?: T;
  internalNotes?: T;
  meta?:
    | T
    | {
        locale?: T;
        sourcePath?: T;
        referrer?: T;
        userAgent?: T;
        ipPrefix?: T;
        submittedAt?: T;
      };
  notifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  type?: T;
  to?: T;
  enabled?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  totpEnabled?: T;
  totpSecret?: T;
  backupCodes?:
    | T
    | {
        hash?: T;
        usedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  fullName?: T;
  company?: T;
  country?: T;
  whatsapp?: T;
  role?: T;
  preferredLocale?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Navigation, contact details and social links. Changes go live immediately.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * E.164 with the plus, e.g. +8613023440305. Powers the floating WhatsApp button on every page.
   */
  whatsappNumber: string;
  /**
   * Optional message pre-filled when someone taps the button, in the language of the page they were on.
   */
  whatsappPrefill?: string | null;
  email: string;
  secondaryEmail?: string | null;
  phone?: string | null;
  offices?:
    | {
        city: string;
        address?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. Sunday–Thursday, 09:00–18:00 China time.
   */
  workingHours?: string | null;
  primaryNav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    instagram?: string | null;
    youtube?: string | null;
    facebook?: string | null;
    tiktok?: string | null;
    linkedin?: string | null;
  };
  /**
   * Used in the Organization structured data.
   */
  organisationName: string;
  /**
   * One line. Shown in link previews and search results.
   */
  tagline?: string | null;
  /**
   * Falls back to the brand OG image in /brand/social if left empty. 1200 × 630.
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Shown as “last updated” on the privacy and terms pages.
   */
  legalUpdatedAt?: string | null;
  /**
   * Shown in the footer if filled in.
   */
  companyRegistration?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  whatsappNumber?: T;
  whatsappPrefill?: T;
  email?: T;
  secondaryEmail?: T;
  phone?: T;
  offices?:
    | T
    | {
        city?: T;
        address?: T;
        id?: T;
      };
  workingHours?: T;
  primaryNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        youtube?: T;
        facebook?: T;
        tiktok?: T;
        linkedin?: T;
      };
  organisationName?: T;
  tagline?: T;
  defaultOgImage?: T;
  legalUpdatedAt?: T;
  companyRegistration?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}